-- PostgreSQL quiz database

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

CREATE user quiz_user WITH ENCRYPTED PASSWORD 'quiz_password';
GRANT all PRIVILEGES ON DATABASE quizzDB TO quiz_user;

-- Table structure for table "questions"
CREATE TABLE IF NOT EXISTS public.questions(
    id smallint NOT NULL PRIMIMARY KEY,
    text character varying(1000) NOT NULL,

)

ALTER TABLE public.questions OWNER TO quiz_user;

-- Table structure for table "answers"
CREATE TABLE IF NOT EXISTS public.answers(
    id smallint NOT NULL PRIMIMARY KEY,
    text character varying(500) NOT NULL,
    is_correct boolean NOT NULL,
    question_id smallint NOT NULL,
    CONSTRAINT fk_question FOREIGN KEY(question_id) REFERENCES public.questions(id) 
    ON DELETE CASCADE ON UPDATE CASCADE
)


CREATE INDEX idx_question_id ON public.answers USING btree (question_id);

ALTER TABLE public.answers OWNER TO quiz_user;


-- games table

CREATE TABLE IF NOT EXISTS public.game (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_offset smallint NOT NULL DEFAULT 0,
  questions_asked smallint NOT NULL DEFAULT 10,
  timeout_answered smallint NOT NULL DEFAULT 5,
  score_correct smallint NOT NULL DEFAULT 1,
  score_fastest smallint NOT NULL DEFAULT 1,
  score_incorrect smallint NOT NULL DEFAULT -1,
  score_noanswer smallint NOT NULL DEFAULT 0,
  time_created timestamp NOT NULL DEFAULT NOW(),
  time_started timestamp NULL DEFAULT NULL
);

CREATE INDEX idx_game_time_created ON public.game USING btree (time_created);

ALTER TABLE public.game OWNER TO quiz_user;

-- game player 

CREATE TABLE IF NOT EXISTS public.game_player(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id integer NOT NULL,
    type character varying(50) NOT NULL,
    data jsonb NOT NULL,
    queued timestamp NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_game FOREIGN KEY(game_id) REFERENCES public.game(id) 
    ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE INDEX player_game_id_idx ON public.game_player USING btree (game_id);

ALTER TABLE public.game_player OWNER TO quiz_user;


-- PUBSUB TABLE

CREATE TABLE IF NOT EXISTS public.pubsub(
    game_id integer NOT NULL PRIMARY KEY,
    type character varying(50) NOT NULL,
    data jsonb NOT NULL,
    queued timestamp NOT NULL DEFAULT NOW(),    
    CONSTRAINT fk_game_pubsub FOREIGN KEY(game_id) REFERENCES public.game(id) 
    ON DELETE CASCADE ON UPDATE CASCADE
)


-- pub sub notification trigger 


CREATE OR REPLACE FUNCTION pubsub_insert_notify()
    RETURNS trigger AS
$BODY$
    BEGIN
        PERFORM pg_notify('pubsub_insert', row_to_json(NEW)::text);
        RETURN NULL;
    END;
$BODY$
    LANGUAGE plpgsql VOLATILE
    COST 100;

CREATE TRIGGER "pubsub_insert_trigger" AFTER INSERT ON public.pubsub FOR EACH ROW EXECUTE FUNCTION pubsub_insert_notify();